preload = ~/Pictures/carbonfox1.jpg
preload = ~/Pictures/carbonfox2.jpg
preload = ~/Pictures/carbonfox3.jpg
preload = ~/Pictures/carbonfox4.jpg
preload = ~/Pictures/carbonfox5.jpg

wallpaper = ,~/Pictures/carbonfox5.jpg
